# Generated by Django 6.0 on 2026-01-06 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 6, 0, 28, 23, 642454)),
        ),
    ]
