# Generated by Django 6.0 on 2026-01-08 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 7, 19, 38, 50, 826033)),
        ),
    ]
