# Generated by Django 6.0 on 2026-01-13 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 0, 6, 0, 645275)),
        ),
    ]
